#!/bin/bash

#SBATCH --time=00:30:00   # walltime
#SBATCH --ntasks=1   # number of processor cores (i.e. tasks)
#SBATCH --nodes=1  # number of nodes
#SBATCH --mem-per-cpu=8000M   # memory per CPU core


sampleId=$1
datasetId=$2
probeSummaryPackage=$3

/fslhome/aguyer/software/R-3.2.2/bin/Rscript --vanilla scanNormalize.r $sampleId $datasetId $probeSummaryPackage
